### ISSUE TITLE
Background FP not counted in specific situation

### ISSUE THREAD

**Issue by kaiakiy** [kaanakan/object_detection_confusion_matrix#16]
I found `process_batch()` doesn't count False Positives in the specific situation where no predictions and ground truths are overlapped.

https://github.com/kaanakan/object_detection_confusion_matrix/blob/5df948f00d1d05f3af9a3afa2802edcaa389ff6e/confusion_matrix.py#L88

When there are no overlaps between `detections` and `labels`, `all_matches.shape` would be `(0, )`.
Then the condition `all_matches.shape[0]` returns `False` and the procedure for counting Background FP is skipped.

I would suggest to add a condition in L88 like this:
```
            if not all_matches.shape[0] or ( all_matches.shape[0] and all_matches[all_matches[:, 1] == i].shape[0] == 0 ):
```

**Comment by meng1994412** [comment]
> I found `process_batch()` doesn't count False Positives in the specific situation where no predictions and ground truths are overlapped.
> 
> https://github.com/kaanakan/object_detection_confusion_matrix/blob/5df948f00d1d05f3af9a3afa2802edcaa389ff6e/confusion_matrix.py#L88
> 
> When there are no overlaps between `detections` and `labels`, `all_matches.shape` would be `(0, )`. Then the condition `all_matches.shape[0]` returns `False` and the procedure for counting Background FP is skipped.
> 
> I would suggest to add a condition in L88 like this:
> 
> ```
>             if not all_matches.shape[0] or ( all_matches.shape[0] and all_matches[all_matches[:, 1] == i].shape[0] == 0 ):
> ```

I found this issue too. 

Thanks for the suggestion! It solved the issue.
