### ISSUE TITLE
Wrong index?

### ISSUE THREAD

**Issue by mnslarcher** [kaanakan/object_detection_confusion_matrix#2]
Hi @kaanakan,

From https://github.com/kaanakan/object_detection_confusion_matrix/blob/fe9cd4a54f5bf5ef592467af83f9073a6a2155cc/confusion_matrix.py#L52

I see that you are using the first column as classes but from your description:
https://github.com/kaanakan/object_detection_confusion_matrix/blob/fe9cd4a54f5bf5ef592467af83f9073a6a2155cc/confusion_matrix.py#L47

classes are in the last column (-1), right?

**Comment by kaanakan** [comment]
Hi,

thank you for your raising this issue. I think the code is correct but the comment is wrong. When implementing, I assumed the labels is a tensor with size (M, 5) consisting of class, x1, y1, x2, y2. 

However, in the comment it says x1, y1, x2, y2, class. So, I should change the comment. It will be updated in 1-2 days.

Thank you.
