### ISSUE TITLE
Few queries about the last column calculation of the confusion matrix

### ISSUE THREAD

**Issue by malarsaravanan1991** [kaanakan/object_detection_confusion_matrix#3]
Thank you for the pytorch implementation.
The last row in the confusion matrix are the false positives(the object detection that are not part of the confusion matrix)so isnt the below code :
       for i, detection in enumerate(detections):
            if all_matches.shape[0] and all_matches[all_matches[:, 1] == i].shape[0] == 1:
supposed to look like the one below:
      **for i, detection in enumerate(detections):
            if all_matches.shape[0] and all_matches[all_matches[:, 1] == i].shape[0] == 0:**

**Comment by YAOYI626** [comment]
I find this bug too, it locates [here](https://github.com/kaanakan/object_detection_confusion_matrix/blob/05acd1eb2ee0f7b08a1fa9cf777230b975a56859/confusion_matrix.py#L83).

**Comment by kaanakan** [comment]
Hi,

Thank you for your post. I have fixed the implementation accordingly, see 64f958eb6498c6fdc8f8d2503e55e57639eeaeda.

For further question, please feel free to ask. I will leave this issue as open. Feel free to close it.
