### ISSUE TITLE
Setting

### ISSUE THREAD

**Issue by ghost** [kaanakan/object_detection_confusion_matrix#4]
Hi @kaanakan  can you please tell me how to make seeting when i have ground truth and prediction coordinates?

**Comment by kaanakan** [comment]
Hi,

As it is stated in the readme, 

first, you need to define a ConfusionMatrix  object with appropriate variables, number of classes and thresholds. For example, 


`conf_mat = ConfusionMatrix(num_classes = 3, CONF_THRESHOLD = 0.3, IOU_THRESHOLD = 0.5)`

Then, you can process batches as this:

`conf_mat.process_batch(preds, gt_boxes)` where preds are predictions made by model, [N, 6] x1, y1, x2, y2, confidence, class and gt_boxes are the ground truth labels, [M, 4] x1, y1, x2, y2, class.

I am closing this issue. If you have any questions, please feel free to open it.
