### ISSUE TITLE
Confusion matrix background fp and background fn are misplaced if matrix is normalized

### ISSUE THREAD

**Issue by rbavery** [kaanakan/object_detection_confusion_matrix#8]
The solution is to swap them, see https://github.com/ultralytics/yolov5/issues/2071 for the issue details with examples and https://github.com/ultralytics/yolov5/pull/2114 for the fix.

**Comment by kaanakan** [comment]
Thank you for the update. I read all of your comments in the issues. 

I updated the repository accordingly. Again, thanks for the update.

**Comment by rbavery** [comment]
Great thanks for fixing!
